### ISSUE TITLE
Maven Build

### ISSUE THREAD

**Issue by hanynowsky** [agorava/agorava-socializer#5]
Am I wrong or it's not possible to build the current branch? (0.7.0-S not yet present in Maven Repo?)

I get this error : 
mvn -Prun
[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.agorava:agorava-socializer:0.7.0-SNAPSHOT (/home/hanine/Workspace/jboss/agorava-socializer/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Failure to find org.agorava:agorava-parent:pom:0.7.0-SNAPSHOT in http://repository.jboss.org/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of jboss-public-repository-group has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 21, column 13 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by keilw** [comment]
As of now, the CloudBees Snapshot Repo no longer works either.

**Comment by keilw** [comment]
All essential repositories moved away from CloudBees, so I suppose this can be closed.
